version: 0.0
os: linux
files:
  - source: /
    destination: /
hooks:
  BeforeInstall:
      timeout: 300
      runas: root
  AfterInstall:
      timeout: 300
      runas: root
  ApplicationStart:
      timeout: 300
      runas: root
  ApplicationStop:
      timeout: 300
      runas: root
